apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher-1s-2r
spec:
  selector:
    matchLabels:
      app: publisher-1s-2r
  replicas: 1
  template:
    metadata:
      labels:
        app: publisher-1s-2r
    spec:
      serviceAccountName: publisher
      containers:
      - name: main
        image: gcr.io/pubsub-test-pull/publisher:v37
        env:
        - name: DELAY_BETWEEN_MESSAGES
          value: "1000"
        - name: PUBSUB_PROJECT_ID
          value: "pubsub-test-pull"
        - name: PUBSUB_TOPIC_ID
          value: "projects/pubsub-test-pull/topics/streaming-pull-1s-2r"
        - name: NUMBER_OF_PULLER_REPLICAS
          value: "2"
        - name: PUBSUB_TOPIC_KIND
          value: "classic"