steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - gcr.io/pubsub-test-pull/pubsub-puller:$SHORT_SHA
      - '--build-arg=JAR_FILE=target/puller-1.0-SNAPSHOT.jar'
      - .
    id: Dockerize
    dir: 'puller/src'
images:
  - gcr.io/pubsub-test-pull/pubsub-puller:$SHORT_SHA